### ISSUE TITLE
Subscript out of range [s:e]

### ISSUE THREAD

**Issue by astrocoolin** [PeterKamphuis/FAT#17]
Error message:

Subscript out of range [s:e]
Execution halted at: FAT               1991 /home/colin/Documents/Work/PhD/Codes/FAT/FAT/FAT.pro

In the galaxy([files.tar.gz](https://github.com/PeterKamphuis/FAT/files/2099556/files.tar.gz)) I'm trying to fit, norings[0] = 9 (and therefore rings[0:8] is the array I think?), but the following line tries to place a vector with length 10 into a vector with length 9

rings[0:9]=(findgen(10))*catmajbeam[i]+catmajbeam[i]/5. 

when I work around there is an error on line 1992:

rings[10:norings[0]-1]=(findgen(fix(tmpring)))*catmajbeam[i]*2+catmajbeam[i]/5.+11.*catmajbeam[i]

where tmpring=norings[0]-10. If tmpring = -1, then findgen(fix(tmpring)) returns an error

**Comment by PeterKamphuis** [comment]
Hi Colin,

I just checked the code and this error should be impossible as finishafter=2.1 only occurs for very large galaxies with maxrings > 25 which would mean your SoFiA mask is much larger than the actual model size? In any case I have added a condition to check that the number of rings is large to make sure this is now impossible.

Let me know if you still have problems.

Cheers,
Peter
